import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0e1c2f",
        "tertiary-fixed": "#ffdcc3",
        "on-error-container": "#93000a",
        "on-secondary-container": "#3b5a7f",
        "inverse-surface": "#2d3133",
        "outline": "#75777d",
        "primary-fixed": "#d6e3fe",
        "primary-container": "#0e1c2f",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d3e4ff",
        "tertiary-container": "#2f1500",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "error": "#ba1a1a",
        "on-primary-container": "#77849c",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#aac9f4",
        "on-primary-fixed-variant": "#3a475c",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "background": "#f7f9fb",
        "primary": "#0b192c",
        "surface-tint": "#525f75",
        "secondary-container": "#b3d1fd",
        "on-tertiary-fixed": "#2f1500",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#c76c00",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "primary-fixed-dim": "#bac7e1",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#44474c",
        "tertiary-fixed-dim": "#ffb77d",
        "outline-variant": "#c5c6cd",
        "surface": "#f7f9fb",
        "on-secondary-fixed-variant": "#29486d",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#001c38",
        "tertiary": "#d97706",
        "secondary": "#1e3e62",
        "surface-variant": "#e0e3e5",
        "inverse-primary": "#bac7e1",
        "on-surface": "#191c1e",
        gov: {
          navy: '#0b192c',
          dark: '#081424',
          blue: '#1e3e62',
          accent: '#426086',
          saffron: '#d97706',
          gold: '#f59e0b',
          green: '#059669',
          crimson: '#dc2626',
          bg: '#f7f9fb',
          card: '#ffffff',
          border: '#e2e8f0',
        },
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "label-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "display": ["IBM Plex Sans", "sans-serif"],
        "cadastral-code": ["JetBrains Mono", "monospace"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-md": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg": ["15px", { "lineHeight": "22px", "fontWeight": "400" }],
        "label-lg": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-sm": ["10px", { "lineHeight": "12px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "display": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "cadastral-code": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
